### ISSUE TITLE
On the Field-II code ...

### ISSUE THREAD

**Issue by bmiftah** [potto216/matlab#1]
Thank you very much for sharing the simulation codes ... I was trying to use them to learn from your simulaiton .. but since I couldnt get readme file , i try to explore by my own. Unfortunatley , i didnt succeed in rununing any one of them successfully - not because of code having error  , but there seems to be usage problem on my side. My question is - where should I start using this code - some need parameter to be passed or some need to be run following execution of the other ... I appreciate any guide or tip you might share on how to use the code , thank you so much

**Comment by potto216** [comment]
Have you been able to run the [Field II software](https://field-ii.dk/) and the [official examples](https://field-ii.dk/?examples.html), specifically the B-Mode examples?

**Comment by bmiftah** [comment]
Yes. I run some demo in Field-II offcial examples ,such as B-Mode for Cyst phantom which is shown hereunder and other simple demo ... except the example for **[PW part](https://field-ii.dk/?examples/pw_example/example_pw_phantom.html)** which didnt work for me.
![Cyst_phantom](https://user-images.githubusercontent.com/28997140/189256480-430ec513-b283-46d6-aa60-0eb4eb91ffc9.jpg)

**Comment by potto216** [comment]
Well that is good then you should be able to run the code. Unfortunately, I don't have Matlab anymore so I cannot test it. I have a [video](https://www.youtube.com/watch?v=cmtpZCIGA_M) on using it.  I think this should work for a demo:
```
objFieldII = objFieldIISetup('ultrasonix')
makeImage
```

**Comment by bmiftah** [comment]
Thank you once again. I run your code and while the first line display basic inf of the object named ObjFieldII , the second line throw error " Unrecognized field name "package"." I watched that video demo , it was helpful but there was little mentioned about the steps to run the codes. While I admire your effort to share those codes, I also want to share this  -  related readme will make your code much much usable to people new to this feild , such as me. - you will help many people with one single effort ... hope you will conisder doing this in one good mood day! Thank you
